### PR TITLE
Fix #88: Add tests for SCA

### LINKED ISSUE #88: Add tests for SCA
Add tests for SCA.
In case face verification fails, go to the OTP verification step and inform user about error after OTP verification. The user should not be able to differentiate the reason for failure.
https://github.com/wultra/enrollment-server/issues/302

### PR DESCRIPTION
**Pull request by banterCZ**
Depends on https://github.com/wultra/enrollment-server/pull/303 and https://github.com/wultra/enrollment-server-wultra/pull/37

### CODE REVIEW

File: powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java [hunk 1]
```diff
@@ -162,19 +162,35 @@ void setUp() throws IOException {
 
     @Test
     void testSuccessfulIdentityVerification() throws Exception {
-        String[] context = prepareActivation();
-        String activationId = context[0];
-        String processId = context[1];
+        final TestContext context = prepareActivation();
```
Comment (banterCZ) [inline powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java:165]: I have created a new context object. Passing more parameters of the same type is error prone.

File: powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java [hunk 2]
```diff
@@ -184,26 +200,56 @@ void testSuccessfulIdentityVerification() throws Exception {
...
 
-        IdentityVerificationState idState =
-                new IdentityVerificationState(IdentityVerificationPhase.PRESENCE_CHECK, IdentityVerificationStatus.NOT_INITIALIZED);
-        assertIdentityVerificationStateWithRetries(idState);
+        assertIdentityVerificationStateWithRetries(
+                new IdentityVerificationState(IdentityVerificationPhase.PRESENCE_CHECK, IdentityVerificationStatus.NOT_INITIALIZED));
+    }
+
+    @Test
+    void testScaFailedPresenceCheck() throws Exception {
```
Comment (banterCZ) [inline powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java:208]: The main change, a new test case.

File: powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java [hunk 3]
```diff
@@ -184,26 +200,56 @@ void testSuccessfulIdentityVerification() throws Exception {
...
+            assertIdentityVerificationStateWithRetries(
+                    new IdentityVerificationState(IdentityVerificationPhase.PRESENCE_CHECK, IdentityVerificationStatus.NOT_INITIALIZED));
+            verifyProcessNotFinished(processId);
+        }
+
+        powerAuthClient.removeActivation(activationId, "test");
+    }
+
+    @Test
+    void testScaFailedOtpCheck() throws Exception {
```
Comment (banterCZ) [inline powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java:229]: The main change, a new test case.

File: powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java [hunk 4]
```diff
@@ -184,26 +200,56 @@ void testSuccessfulIdentityVerification() throws Exception {
...
-                new IdentityVerificationState(IdentityVerificationPhase.PRESENCE_CHECK, IdentityVerificationStatus.NOT_INITIALIZED);
-        assertIdentityVerificationStateWithRetries(idState);
+        assertIdentityVerificationStateWithRetries(
+                new IdentityVerificationState(IdentityVerificationPhase.PRESENCE_CHECK, IdentityVerificationStatus.NOT_INITIALIZED));
+    }
+
+    @Test
+    void testScaFailedPresenceCheck() throws Exception {
+        // instruction for WultraMockPresenceCheckProvider#getResult(OwnerId, SessionInfo) to fail
+        final TestContext context = prepareActivation("_PRESENCE_CHECK_REJECTED");
```
Comment (banterCZ) [inline powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java:210]: See https://github.com/wultra/enrollment-server-wultra/pull/37

File: powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java [hunk 5]
```diff
@@ -1057,14 +1124,17 @@ private void verifyOtpCheck(String processId) throws Exception {
...
-                }
+                otpVerified = stepLogger.getItems().stream()
+                        .filter(isStepItemDecryptedResponse())
+                        .map(StepItem::getObject)
+                        .map(Object::toString)
+                        .map(it -> safeReadValue(it, new TypeReference<ObjectResponse<OtpVerifyResponse>>() {}))
+                        .filter(Objects::nonNull)
+                        .map(ObjectResponse::getResponseObject)
+                        .map(OtpVerifyResponse::isVerified)
+                        .findFirst()
```
Comment (banterCZ) [inline powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthIdentityVerificationTest.java:1135]: Stream and its `#findFirst` makes it _short-circuit evaluation_, or it may be extracted to a method.

**Review by saalistaja — APPROVED** [review]
Looks good.

**Review by romanstrobl — APPROVED** [review]
Looks OK.
