### PR TITLE
Fix #791: Fix failing onboarding tests

### LINKED ISSUE #791: Fix failing onboarding tests
### Affected product(s) and version(s)

_No response_

### Environment

_No response_

### Steps to reproduce, current result, expected result

See https://github.com/wultra/powerauth-tests/runs/59863717870

### Log output

_No response_

### PR DESCRIPTION
**Pull request by michal-rozehnal-w**
The real fix was done in this PR https://github.com/wultra/enrollment-server/pull/1460
All tests on this branch are passing now https://github.com/wultra/powerauth-tests/actions/runs/20910318137

### CODE REVIEW

File: powerauth-backend-tests/src/test/resources/data/enrollment-onboarding/extra-data.sql [hunk 1]
```diff
@@ -1,3 +1,3 @@
 INSERT INTO es_onboarding_process_configuration (id, process_type, config) VALUES
-    (1, 'reactivation', '{"enabled":true,"activationType":"IDENTITY","otpForIdentification":true,"otpForIdentityVerification":true,"documents":{"totalRequiredDocumentsCount":2,"groups":[{"requiredDocumentsCount":2,"items":[{"type":"ID_CARD","sideCount":2},{"type":"DRIVING_LICENCE","sideCount":1}]}]}}'),
-    (2, 'onboarding', '{"enabled":true,"activationType":"CODE","otpForIdentification":false,"otpForIdentityVerification":false,"documents":{"totalRequiredDocumentsCount":2,"groups":[{"requiredDocumentsCount":2,"items":[{"type":"ID_CARD","sideCount":2},{"type":"DRIVING_LICENCE","sideCount":1}]}]}}');
+    (1, 'reactivation', '{"enabled":true,"activationType":"IDENTITY","otpForIdentification":true,"otpForIdentityVerification":true,"documents":{"totalRequiredDocumentsCount":2,"groups":[{"requiredDocumentsCount":1,"items":[{"type":"ID_CARD","sideCount":2}]},{"requiredDocumentsCount":1,"items":[{"type":"PASSPORT","sideCount":1},{"type":"DRIVING_LICENCE","sideCount":1}]}]}}'),
```
Comment (michal-rozehnal-w) [inline powerauth-backend-tests/src/test/resources/data/enrollment-onboarding/extra-data.sql:2]: Just making the config the same as it was previously in application.properties. Two documents are required: one must be `ID_CARD`, and the second can be either `PASSPORT` or `DRIVING_LICENCE`.

Comment (banterCZ) [reply powerauth-backend-tests/src/test/resources/data/enrollment-onboarding/extra-data.sql:2]: Great, this configuration is expected.

**Review by banterCZ — APPROVED** [review]
