### PR TITLE
Fix #100: Test for maximum failed OTP verification attempts

### LINKED ISSUE #100: Test for maximum failed OTP verification attempts
Prepare additional tests for use cases:
https://github.com/wultra/enrollment-server/issues/261
https://github.com/wultra/enrollment-server/issues/269

### PR DESCRIPTION
**Pull request by romanstrobl**
Test for remaining attempts during activation using OTP code verification.

### CODE REVIEW

File: powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java [hunk 1]
```diff
@@ -274,15 +276,18 @@ void testMaxAttemptsReached() throws Exception {
         // Obtain activation OTP from testing endpoint
         String otpCode = getOtpCode(processId);
 
-        for (int i = 0; i < 5; i++) {
-            assertThrows(AssertionFailedError.class, () ->
-                    createCustomActivation(processId, "0000000000", clientId),
-                    "Activation with invalid OTP should fail");
+        for (int i = 0; i < 4; i++) {
```
Comment (banterCZ) [inline powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java:279]: What about to invert the `for` statement? Just thinking. Isn't it weird?
```suggestion
        for (int i = 4; i > 0; i--) {
```

**Review by banterCZ — APPROVED** [review]

File: powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java (hunk 1 above)
Comment (romanstrobl) [reply powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/v31/PowerAuthOnboardingTest.java]: Sure.
