### PR TITLE
Fix: Remove recovery code tests #589, cleanup code for crypto4

### LINKED ISSUE #589: Remove recovery code tests
### Task specification

The recovery code functionality is deprecated in crypto4 project.

### PR DESCRIPTION
**Pull request by romanstrobl**
This pull request contains following changes:

- Fix #589: Remove recovery code tests
- code cleanup for crypto4 (update ECIES encryption model and API, fix deprecations)

### CODE REVIEW

File: powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/shared/PowerAuthApiShared.java [hunk 1]
```diff
@@ -223,148 +219,20 @@ public static void createValidateAndRemoveTokenTestActiveActivation(PowerAuthCli
         assertTrue(removeResponse.isRemoved());
     }
 
-    public static void recoveryCodeConfirmAndActivationTest(PowerAuthClient powerAuthClient, PowerAuthTestConfiguration config, PowerAuthVersion version) throws Exception {
-        String activationName = "test_create_recovery";
-        KeyPair deviceKeyPair = CLIENT_ACTIVATION.generateDeviceKeyPair();
```
Comment (jnpsk) [inline powerauth-backend-tests/src/test/java/com/wultra/security/powerauth/test/shared/PowerAuthApiShared.java:228]: The `CLIENT_ACTIVATION` is now unused by the class.

**Review by jnpsk — APPROVED** [review]
Looks ok
